INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX,GRADE,COUNTRY) values(101, 'Nagaraj', 25, 'M','UG','INDIA');
INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX,GRADE,COUNTRY) values(102, 'Karthik', 26, 'M','PG','USA');
INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX,GRADE,COUNTRY) values(103, 'Dhamo', 39, 'M','UG','CANADA');
INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX,GRADE,COUNTRY) values(104, 'Savithri', 37, 'F','PG','SRILANKA');