INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX) values(101, 'Nagaraj', 25, 'M');
INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX) values(102, 'Karthik', 26, 'M');
INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX) values(103, 'Dhamo', 39, 'M');
INSERT INTO STUDENT_INFO (ROLLNUM, NAME, AGE, SEX) values(104, 'Savithri', 37, 'F');